### ISSUE TITLE
Loading feedback when certain actions are not immediate

### ISSUE THREAD

**Issue by lukecotter** [financialforcedev/debug-log-analyzer#18] opened 2021-03-03 11:28 UTC
### Is your feature request related to a problem?
When using the `Log: Load Apex Log for Analysis` command it takes a bit of time to open the select a log file palette.
There is a similar wait after selecting a log and before the log window opens.

### Describe the solution you'd like
Could we have some loading feedback in these cases just so we know something is happening and to wait a bit?

**Comment by nawforce** [comment] 2021-03-03 19:49
Good point, I did think they delays were a bit rubbish but never got to resolving.

The first I think is caused by waiting for the list of logs to come back from sfdx. A simple approach might be to insert a progress step so you know it's happening.  We could perhaps reduce the time taken by rolling our own query and firing via a pre-setup jsforce connection. I don't know how difficult that might be.

The second is likely the download of the log after selection. Same options I would think.

**Comment by nawforce** [comment] 2021-03-03 19:53
If you fancy having a go at them ping me as am planning to start work in swapping out the Scala code. Initially the backend will go from using a scala.js lib to npm module and then the extension itself can be swapped from Scala to TS.

**Closed** 2021-05-14 20:12 UTC
