### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/c:/Users/anesingh/Desktop/ProjectName/DEV/CSDEV/Apex.log'

### ISSUE THREAD

**Issue by singhaneesh02** [financialforcedev/debug-log-analyzer#5] opened 2020-12-11 07:27 UTC
Getting this Error when right clicked on log and selected Show log Analysis

Machine OS : - Windows 10
Vs code version :- Recent

**Comment by kjonesffdc** [comment] 2020-12-11 08:19
Duplicate of #4

**Comment by kjonesffdc** [comment] 2020-12-11 12:51
This has been fixed in 1.3.4 so I will close.

**Closed by kjonesffdc** 2020-12-11 12:51 UTC
